/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_23 (
    input [5:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] out,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [15:0] tempresult;
  
  reg xb;
  
  always @* begin
    out = 1'h0;
    z = 1'h0;
    v = 1'h0;
    n = 1'h0;
    
    case (alufn[0+5-:6])
      6'h00: begin
        out = $signed(a) + $signed(b);
        tempresult = $signed(a) + $signed(b);
      end
      6'h01: begin
        out = $signed(a) - $signed(b);
        tempresult = $signed(a) - $signed(b);
        xb = b[15+0-:1] ^ alufn[0+0-:1];
        if (tempresult == 1'h0) begin
          z = 1'h1;
        end else begin
          z = 1'h0;
        end
        n = tempresult[15+0-:1];
        v = (a[15+0-:1] & xb & (~tempresult[15+0-:1])) | (~a[15+0-:1] & ~xb & tempresult[15+0-:1]);
      end
    endcase
  end
endmodule
