/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module generator_bottom_3 (
    input clk,
    input rst,
    input [0:0] button_l,
    input [0:0] button_r,
    input [31:0] rows,
    output reg [31:0] rowsout,
    output reg led
  );
  
  
  
  wire [16-1:0] M_alu_out;
  wire [1-1:0] M_alu_z;
  wire [1-1:0] M_alu_v;
  wire [1-1:0] M_alu_n;
  reg [16-1:0] M_alu_a;
  reg [16-1:0] M_alu_b;
  reg [6-1:0] M_alu_alufn;
  alu_10 alu (
    .a(M_alu_a),
    .b(M_alu_b),
    .alufn(M_alu_alufn),
    .out(M_alu_out),
    .z(M_alu_z),
    .v(M_alu_v),
    .n(M_alu_n)
  );
  
  localparam XOR = 6'h16;
  
  localparam SHL = 6'h20;
  
  localparam SHR = 6'h21;
  
  reg [15:0] M_xoroutput_d, M_xoroutput_q = 1'h0;
  reg [31:0] M_shiftleft_d, M_shiftleft_q = 1'h0;
  reg [31:0] M_shiftright_d, M_shiftright_q = 1'h0;
  localparam IDLE_new_fsm = 2'd0;
  localparam LEFT_new_fsm = 2'd1;
  localparam RIGHT_new_fsm = 2'd2;
  
  reg [1:0] M_new_fsm_d, M_new_fsm_q = IDLE_new_fsm;
  
  always @* begin
    M_new_fsm_d = M_new_fsm_q;
    M_xoroutput_d = M_xoroutput_q;
    M_shiftright_d = M_shiftright_q;
    M_shiftleft_d = M_shiftleft_q;
    
    rowsout[0+15-:16] = 16'h0000;
    rowsout[16+15-:16] = 16'h0000;
    led = 8'h00;
    M_alu_a = 1'h0;
    M_alu_b = 1'h0;
    M_alu_alufn = 1'h0;
    rowsout = rows;
    
    case (M_new_fsm_q)
      IDLE_new_fsm: begin
        M_alu_a = button_l;
        M_alu_b = button_r;
        M_alu_alufn = 6'h16;
        M_xoroutput_d = M_alu_out;
        if (button_l == 1'h1 && M_xoroutput_q == 16'h0001) begin
          M_new_fsm_d = LEFT_new_fsm;
        end
        if (button_r == 1'h1 && M_xoroutput_q == 16'h0001) begin
          M_new_fsm_d = RIGHT_new_fsm;
        end
      end
      RIGHT_new_fsm: begin
        if (rows[0+1+0-:1] != 1'h1) begin
          M_alu_a = rows[0+15-:16];
          M_alu_b = 1'h1;
          M_alu_alufn = 6'h21;
          M_shiftright_d[0+15-:16] = M_alu_out;
          M_alu_a = rows[16+15-:16];
          M_alu_b = 1'h1;
          M_alu_alufn = 6'h21;
          M_shiftright_d[16+15-:16] = M_alu_out;
          rowsout = M_shiftright_q;
        end
        M_new_fsm_d = IDLE_new_fsm;
      end
      LEFT_new_fsm: begin
        if (rows[0+14+0-:1] != 1'h1) begin
          M_alu_a = rows[0+15-:16];
          M_alu_b = 1'h1;
          M_alu_alufn = 6'h20;
          M_shiftleft_d[0+15-:16] = M_alu_out;
          M_alu_a = rows[16+15-:16];
          M_alu_b = 1'h1;
          M_alu_alufn = 6'h20;
          M_shiftleft_d[16+15-:16] = M_alu_out;
          rowsout = M_shiftleft_q;
        end
        M_new_fsm_d = IDLE_new_fsm;
      end
    endcase
  end
  
  always @(posedge clk) begin
    M_xoroutput_q <= M_xoroutput_d;
    M_shiftleft_q <= M_shiftleft_d;
    M_shiftright_q <= M_shiftright_d;
    
    if (rst == 1'b1) begin
      M_new_fsm_q <= 1'h0;
    end else begin
      M_new_fsm_q <= M_new_fsm_d;
    end
  end
  
endmodule
