/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_19 (
    input [5:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] c
  );
  
  
  
  always @* begin
    
    case (alufn[0+5-:6])
      6'h20: begin
        c = a << b[0+2-:3];
      end
      6'h21: begin
        c = a >> b[0+2-:3];
      end
      6'h23: begin
        c = $signed(a) >>> b[0+2-:3];
      end
      default: begin
        c = a;
      end
    endcase
  end
endmodule
