/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module timer_10 (
    input clk,
    input rst,
    output reg out,
    output reg [9:0] timebar,
    output reg final
  );
  
  
  
  reg [29:0] M_countdown_d, M_countdown_q = 1'h0;
  localparam FIRST_ITR_newfsm = 1'd0;
  localparam SECOND_ITR_newfsm = 1'd1;
  
  reg M_newfsm_d, M_newfsm_q = FIRST_ITR_newfsm;
  reg [9:0] M_time_store_d, M_time_store_q = 1'h0;
  
  always @* begin
    M_newfsm_d = M_newfsm_q;
    M_countdown_d = M_countdown_q;
    M_time_store_d = M_time_store_q;
    
    out = 1'h0;
    final = 1'h0;
    timebar = M_time_store_q;
    M_countdown_d = M_countdown_q + 1'h1;
    
    case (M_newfsm_q)
      FIRST_ITR_newfsm: begin
        M_time_store_d = 10'h3ff;
        M_newfsm_d = SECOND_ITR_newfsm;
      end
      SECOND_ITR_newfsm: begin
        if (M_countdown_q == 29'h11e1a2ff) begin
          M_time_store_d = M_time_store_q << 1'h1;
          timebar = M_time_store_q;
          M_countdown_d = 1'h0;
        end else begin
          M_time_store_d = M_time_store_q;
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    M_time_store_q <= M_time_store_d;
    
    if (rst == 1'b1) begin
      M_countdown_q <= 1'h0;
      M_newfsm_q <= 1'h0;
    end else begin
      M_countdown_q <= M_countdown_d;
      M_newfsm_q <= M_newfsm_d;
    end
  end
  
endmodule
